
// Build.gradle generated for instrumentation module camel-kafka

apply plugin: 'java'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}



dependencies {
   	implementation 'org.apache.camel:camel-kafka:3.21.4'

   // New Relic Labs Java Agent dependencies
   implementation 'com.newrelic.agent.java:newrelic-agent:' + project.findProperty('java.agent.version')
   implementation 'com.newrelic.agent.java:newrelic-api:' + project.findProperty('java.agent.version')
   implementation 'com.newrelic.agent.java:agent-bridge:' + project.findProperty('java.agent.version')
}

jar {
  manifest {
    attributes 'Implementation-Title': 'com.newrelic.instrumentation.labs.camel-kafka-3.21.4'
    attributes 'Implementation-Vendor': 'New Relic Labs'
    attributes 'Implementation-Vendor-Id': 'com.newrelic.labs'
    attributes 'Implementation-Version': 1.0
  }
}

verifyInstrumentation {
    passesOnly 'org.apache.camel:camel-kafka:[3.21.4,3.22.0)'
 }
