
// Build.gradle generated for instrumentation module camel-cfx

apply plugin: 'java'

dependencies {
   implementation group: 'org.apache.camel', name: 'camel-cxf', version: '3.0.0'


   // New Relic Labs Java Agent dependencies
   implementation 'com.newrelic.agent.java:newrelic-agent:' + project.findProperty('java.agent.version')
   implementation 'com.newrelic.agent.java:newrelic-api:' + project.findProperty('java.agent.version')
   implementation 'com.newrelic.agent.java:agent-bridge:' + project.findProperty('java.agent.version')
}

jar {
  manifest {
    attributes 'Implementation-Title': 'com.newrelic.instrumentation.labs.camel-cfx'
    attributes 'Implementation-Vendor': 'New Relic Labs'
    attributes 'Implementation-Vendor-Id': 'com.newrelic.labs'
    attributes 'Implementation-Version': 1.0
  }
}

verifyInstrumentation {
  // Verifier plugin documentation:
  // https://github.com/newrelic/newrelic-gradle-verify-instrumentation
  // Example:
  // passesOnly 'javax.servlet:servlet-api:[2.2,2.5]'
  // exclude 'javax.servlet:servlet-api:2.4.public_draft'
}